### ISSUE TITLE
Include new Mint-Y Theme that is coming in Mint 20.3

### ISSUE THREAD

**Issue by joka42** [SebastJava/mint-themes#18]
Hi there, the theme is nice, I just discovered it!
Will you include the new, larger title bars and buttons from the new mint-y themes that are coming in Mint 20.3 in the Mint-YZ theme soon (or at all)? I would love to see that.

**Comment by SebastJava** [comment]
I will think about this. I am thinking about a major re-engineering coming sometime this winter. And I want to start by pulling all the updates from the upstream source. But I will probably pull the latest version from... the old https://github.com/linuxmint/mint-themes-legacy. Not from the new one. I don't like the way they replaced some colours with grey tints on many things on the new Mint-Y.

As for these new title bars, yes, I appreciate having bigger buttons, and I would normally love these new rounded corners, but I don't. Why ? Because I find it weird to see the top part of the window having nice rounded corners, while the bottom part still keeps those old square corners. They just replaced the title bars while still keeping the rest of the old window design, and I don't like that. I would strongly prefer having the four window corners made rounded, not just the top part. And, to make it worst, there is currently an issue about bad rendering for those rounded title bar corners: https://github.com/linuxmint/mint20.3-beta/issues/26

So, I will re-start with the old "legacy" Mint-Y, change the colours again, make the buttons more rounded again, fix some other issues, and then, later, maybe, try to make bigger window title buttons, but without rounded corners on the window title. I would really appreciate to get all four rounded corners on the windows, just like what we have right here in GitHub, but we are currently having some technical difficulties on the Metacity themes (window borders), and this will not be fixed before Mint version 21, sadly.

Say tuned. :)

**Comment by SebastJava** [comment]
P.S.: Are you on Cinnamon ?
You should be able to set Mint-Yz-COLOUR for controls and combine it with the new Mint-Y for window borders, using Menu > Preferences >Themes. So you could easily get what you want, regardless of what this upcoming Mint-Yz will be made of.

**Comment by 392781** [comment]
> I will think about this. I am thinking about a major re-engineering coming sometime this winter. And I want to start by pulling all the updates from the upstream source. But I will probably pull the latest version from... the old https://github.com/linuxmint/mint-themes-legacy. Not from the new one. I don't like the way they replaced some colours with grey tints on many things on the new Mint-Y.
> 
> As for these new title bars, yes, I appreciate having bigger buttons, and I would normally love these new rounded corners, but I don't. Why ? Because I find it weird to see the top part of the window having nice rounded corners, while the bottom part still keeps those old square corners. They just replaced the title bars while still keeping the rest of the old window design, and I don't like that. I would strongly prefer having the four window corners made rounded, not just the top part. And, to make it worst, there is currently an issue about bad rendering for those rounded title bar corners: [linuxmint/mint20.3-beta#26](https://github.com/linuxmint/mint20.3-beta/issues/26)
> 
> So, I will re-start with the old "legacy" Mint-Y, change the colours again, make the buttons more rounded again, fix some other issues, and then, later, maybe, try to make bigger window title buttons, but without rounded corners on the window title. I would really appreciate to get all four rounded corners on the windows, just like what we have right here in GitHub, but we are currently having some technical difficulties on the Metacity themes (window borders), and this will not be fixed before Mint version 21, sadly.
> 
> Say tuned. :)

Just wanted to tell you that you have excellent taste and I absolutely love the work you've done with the original theme.  I look forward to what you have in mind.  I do wish I could contribute, unfortunately I am not at all a UI design buff.

> P.S.: Are you on Cinnamon ? You should be able to set Mint-Yz-COLOUR for controls and combine it with the new Mint-Y for window borders, using Menu > Preferences >Themes. So you could easily get what you want, regardless of what this upcoming Mint-Yz will be made of.

The problem with doing this on the Mint-Yz-Darkest is that the 1 pixel border with the new Mint-Y is white:

![image](https://user-images.githubusercontent.com/25296775/148624512-7d773ab6-5df2-44ff-b4fa-f5344d7a0aa8.png)

**Comment by joka42** [comment]
It works quite well in the light theme. I like the light new light gray in Nemo's left toolbar. I think that is what you did not like ;-) I guess there is always a tradeoff. Thanks for the suggestion anyway!

**Comment by SebastJava** [comment]
@joka42 

> [...] I like the light new light gray in Nemo's left toolbar. I think that is what you did not like ;-) [...]

Rest assured, I want this light sidebar: https://github.com/SebastJava/mint-yz-theme/issues/26

I don't know how I will do all this, yet. I could start from the old Mint-Y-Legacy, and "copy-paste" all the good improvements one-by-one... Or just take the new Mint-Y and "undo" the few things I don't like. But this light gray sidebar will be included, anyway.

**Comment by SebastJava** [comment]
I am now working on the new Mint-Y. So, these are already done in the coding. :)
It will be available on the next release, coming up sometime before the end of this winter.

Nemo light sidebar: OK
New title bars: OK, but I will probably make all four corners square, as explained there: https://forums.linuxmint.com/viewtopic.php?p=2125185#p2125185
