### ISSUE TITLE
Close button red background seems to be moved from the center

### ISSUE THREAD

**Issue by ti-ago** [SebastJava/mint-themes#38]
It seems to be moved from the center, maybe the "X" is moved, I don't know.

**Comment by SebastJava** [comment]
@ti-ago 
I need more info, please..

* Screenshots ! One image is worth a thousand words...
* on LinuxMint ? version xx.x ? Cinnamon, Mate or Xfce ?
* Also, if possible, could you compare with the standard Mint-Y ?

This Mint-Yz is a fork from Mint-Y. It is very important to know if this bug comes from the upstream source, Mint-Y, or from the modifications done into this fork, here.

Here in this Mint-Yz theme, there is no more background behind the X, except on mouse over and mouse click:

Normal state:
![image](https://user-images.githubusercontent.com/31940713/172028497-cc508a3e-b209-42cb-854a-64bfb967a5a3.png)

Mouse over:
![image](https://user-images.githubusercontent.com/31940713/172028472-75f8d1dc-19f8-4736-86e4-e1c472d97537.png)

That is how it should work. It would really help if you could include some screenshot(s).

Thanks.

**Comment by SebastJava** [comment]
**README presentation now updated** with window close button on focus, mouse hover and mouse click:
https://github.com/SebastJava/mint-yz-theme#readme
(third image from the top)

**Comment by SebastJava** [comment]
Added issue templates for any future issues:
https://github.com/SebastJava/mint-yz-theme/issues/new/choose
(You can still start from a blank page if you want.)

**Comment by SebastJava** [comment]
More info requested. No answer...
